version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: test_app
    restart: always
    ports:
      - '10001:8000'
    env_file: .env
    depends_on:
      - db
    networks:
      - test_network

  db:
    image: postgres:12
    container_name: core_db
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - test_network


networks:
  test_network:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: 10.10.12.0/24